// Code generated by qtc from "export.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line export.qtpl:1
package godeep

//line export.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line export.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line export.qtpl:2
type jsonPackage struct {
	Name       string
	Path       string
	Imported   []string
	ImportedBy []string
	Funcs      []string
	Types      []string
}

type jsonPackages struct {
	Total    int
	Packages []jsonPackage
}

// JSON marshaling

//line export.qtpl:19
func (d *jsonPackages) StreamJSON(qw422016 *qt422016.Writer) {
//line export.qtpl:19
	qw422016.N().S(`{"packages": [`)
//line export.qtpl:22
	for i, r := range d.Packages {
//line export.qtpl:22
		qw422016.N().S(`{"name":`)
//line export.qtpl:24
		qw422016.N().Q(r.Name)
//line export.qtpl:24
		qw422016.N().S(`,"path":`)
//line export.qtpl:25
		qw422016.N().Q(r.Path)
//line export.qtpl:25
		qw422016.N().S(`,"imported":[`)
//line export.qtpl:27
		for i, rr := range r.Imported {
//line export.qtpl:28
			qw422016.N().Q(rr)
//line export.qtpl:29
			if i+1 < len(r.Imported) {
//line export.qtpl:29
				qw422016.N().S(`,`)
//line export.qtpl:29
			}
//line export.qtpl:30
		}
//line export.qtpl:30
		qw422016.N().S(`],"importedBy":[`)
//line export.qtpl:33
		for i, rr := range r.ImportedBy {
//line export.qtpl:34
			qw422016.N().Q(rr)
//line export.qtpl:35
			if i+1 < len(r.ImportedBy) {
//line export.qtpl:35
				qw422016.N().S(`,`)
//line export.qtpl:35
			}
//line export.qtpl:36
		}
//line export.qtpl:36
		qw422016.N().S(`],"exported_funcs":[`)
//line export.qtpl:39
		for i, rr := range r.Funcs {
//line export.qtpl:40
			qw422016.N().Q(rr)
//line export.qtpl:41
			if i+1 < len(r.Funcs) {
//line export.qtpl:41
				qw422016.N().S(`,`)
//line export.qtpl:41
			}
//line export.qtpl:42
		}
//line export.qtpl:42
		qw422016.N().S(`],"exported_types":[`)
//line export.qtpl:45
		for i, rr := range r.Types {
//line export.qtpl:46
			qw422016.N().Q(rr)
//line export.qtpl:47
			if i+1 < len(r.Types) {
//line export.qtpl:47
				qw422016.N().S(`,`)
//line export.qtpl:47
			}
//line export.qtpl:48
		}
//line export.qtpl:48
		qw422016.N().S(`],}`)
//line export.qtpl:52
		if i+1 < len(d.Packages) {
//line export.qtpl:52
			qw422016.N().S(`,`)
//line export.qtpl:52
		}
//line export.qtpl:53
	}
//line export.qtpl:53
	qw422016.N().S(`]}`)
//line export.qtpl:56
}

//line export.qtpl:56
func (d *jsonPackages) WriteJSON(qq422016 qtio422016.Writer) {
//line export.qtpl:56
	qw422016 := qt422016.AcquireWriter(qq422016)
//line export.qtpl:56
	d.StreamJSON(qw422016)
//line export.qtpl:56
	qt422016.ReleaseWriter(qw422016)
//line export.qtpl:56
}

//line export.qtpl:56
func (d *jsonPackages) JSON() string {
//line export.qtpl:56
	qb422016 := qt422016.AcquireByteBuffer()
//line export.qtpl:56
	d.WriteJSON(qb422016)
//line export.qtpl:56
	qs422016 := string(qb422016.B)
//line export.qtpl:56
	qt422016.ReleaseByteBuffer(qb422016)
//line export.qtpl:56
	return qs422016
//line export.qtpl:56
}
